name:                cardano-transactions
version:             1.0.0
github:              "input-output-hk/cardano-transactions"
license:             Apache-2.0
author:              "KtorZ <matthias.benkort@iohk.io>"
maintainer:          "operations@iohk.io, matthias.benkort@iohk.io"
copyright:           "2020 IOHK"
synopsis:            Library utilities for constructing and signing Cardano transactions.
category:            Cardano

extra-source-files:
- README.md
- ChangeLog.md

description: |
  Please see the README on GitHub at <https://github.com/input-output-hk/cardano-transactions>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -fwarn-redundant-constraints
  dependencies:
  - base58-bytestring
  - bytestring
  - cardano-binary
  - cardano-crypto
  - cardano-crypto-wrapper
  - cardano-ledger
  - cborg
  - cryptonite
  - memory
  - text

# executables:
#   cardano-transactions-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - cardano-transactions

tests:
  unit:
    source-dirs: test
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cardano-crypto
    - cardano-crypto-wrapper
    - cardano-ledger
    - cardano-ledger-test
    - cardano-transactions
    - cborg
    - hedgehog-quickcheck
    - hspec
    - QuickCheck
    - text

