name:                cardano-transactions
version:             1.0.0
github:              "input-output-hk/cardano-transactions"
license:             Apache-2.0
author:              IOHK
maintainer:          "operations@iohk.io"
copyright:           "2020 IOHK"
synopsis:            Library utilities for constructing and signing Cardano transactions.
category:            Cardano

extra-source-files:
- README.md
- ChangeLog.md

description: |
  Please see the README on GitHub at <https://github.com/input-output-hk/cardano-transactions>

dependencies:
- base >= 4.7 && < 5

flags:
  release:
    description: Compile executables for a release.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options:
  - -Wcompat
  - -fwarn-redundant-constraints
  dependencies:
  - base58-bytestring
  - bytestring
  - cardano-binary
  - cardano-crypto
  - cardano-crypto-wrapper
  - cardano-ledger
  - cborg
  - cryptonite
  - extra
  - memory
  - text
  when:
  - condition: flag(release)
    ghc-options:
      - -Werror
      - -Wall

executables:
  cardano-tx:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-terminal
    - bytestring
    - cardano-transactions
    - cborg
    - memory
    - optparse-applicative
    - text
    when:
    - condition: flag(release)
      ghc-options:
      - -Werror
      - -Wall
      - -static
      - -O2
      cc-options: -static
      ld-options: -static -pthread

tests:
  unit:
    source-dirs: test
    main: Main.hs
    ghc-options:
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cardano-crypto-wrapper
    - cardano-ledger
    - cardano-ledger-test
    - cardano-transactions
    - cborg
    - hedgehog-quickcheck
    - hspec
    - process
    - QuickCheck
    - text
    build-tools:
      cardano-tx
    when:
    - condition: flag(release)
      ghc-options:
        - -Werror
        - -Wall
